### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [2]:
import numpy as np

In [13]:
arr = np.arange(1000000)
lista = list(range(1000000))
%time arr2 = arr * 2
lista2 = []
%time for x in lista: lista2.append(x*2)

CPU times: user 1.41 ms, sys: 415 µs, total: 1.83 ms
Wall time: 1.83 ms
CPU times: user 89 ms, sys: 20.3 ms, total: 109 ms
Wall time: 109 ms


### Exercício 2

In [15]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
arr = np.arange(10)
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [25]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
arr = np.array([[[0,1,2],[0,1,2],[0,1,2],[0,1,2],[0,1,2],[0,1,2]]])
arr[0][0]

array([0, 1, 2])

### Exercício 4

In [34]:
# Crie um array de duas dimensões (matriz).
arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
# Imprima os elementos da terceira linha da matriz
arr[2]
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr[:2,1:]

array([[1, 2],
       [4, 5]])

### Exercício 5

In [9]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
arr.T

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Exercício 6

In [35]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


In [40]:
cont = 0
for c in cond:    
    if c == True:
        print(xarr[cont])
    else:
        print(yarr[cont])
    cont =+1

1.1
2.2
1.2
1.2
2.2


### Exercício 7

In [41]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
a = np.arange(10)

In [52]:
np.save('array',a)

In [53]:
b = np.load('array.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [56]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

Exception ignored in: <function ZipFile.__del__ at 0x7fe07239a598>
Traceback (most recent call last):
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 1767, in __del__
    self.close()
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 1785, in close
    self._write_end_record()
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 1888, in _write_end_record
    self.fp.write(endrec)
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 736, in write
    n = self.fp.write(data)
AttributeError: 'numpy.ndarray' object has no attribute 'write'
Exception ignored in: <function ZipFile.__del__ at 0x7fe07239a598>
Traceback (most recent call last):
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 1767, in __del__
    self.close()
  File "/home/gabriel/anaconda3/lib/python3.7/zipfile.py", line 1784, in close
    self.fp.seek(self.start_dir)
ValueError: I/O operation on closed file.
Exception ignored in: <function ZipFile.__del__ at 

In [57]:
unico = obj.unique()
unico

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [62]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

In [64]:
json = resp.json()
df = pd.DataFrame(json, columns=['number', 'title', 'labels', 'state'])
df

number                                              title  \
0    24427                      DOC: Removing old release.rst   
1    24426  BUG-24408 Series.dt does not maintain own copy...   
2    24425  to_sql to postgres database，error shows bug on...   
3    24424               Potential bug fixes on shell scripts   
4    24423         Decouple xlrd reading from ExcelFile class   
5    24421               Add ref to docstring of Series:dtype   
6    24419  REF: clearer Categorical/CategoricalIndex cons...   
7    24417  TST: move mi tests from tests/indexing/ to tes...   
8    24416  DEPR: box argument in to_datetime and to_timed...   
9    24415           BUG: to_datetime(Timestamp) utc argument   
10   24414  REF/TST: Add more pytest idiom to resample/tes...   
11   24413       ExtensionArray/Index/Series.repeat signature   
12   24412  BUG: Fix groupby observed=True when aggregatin...   
13   24408  BUG: Series.dt accessor throws exception after...   
14   24405                 implement astype portion of #24024   
15   24404  ValueError when reading a Dataframe with HDFSt...   
16   24399  Allowing custom function for merge as_of "dire...   
17   24398  API: Add dtype parameter to Categorical.from_c...   
18   24397                  BUG: Assorted DTA/TDA/PI bugfixes   
19   24396                    Series of integers mod behavior   
20   24394                                       POC: _eadata   
21   24391  BUG: PeriodIndex._shallow_copy doesn't roundtr...   
22   24390  check overwrite mode in to_csv and other writers.   
23   24388  DataFrame constructor is inconsistent when coe...   
24   24387      PERF: DataFrame dict constructor with columns   
25   24386  DataFrame constructor ignores integer dtype wh...   
26   24385  Series / DataFrame constructors inconsistent w...   
27   24383  BUG: DataFrame.loc/iloc fails to update object...   
28   24382  Implement min, argmin, max, argmax on Extensio...   
29   24381  Datetimelike index / arrays ignore integer sig...   

                                               labels state  
0   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
1                                                  []  open  
2                                                  []  open  
3   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
4   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
5   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
6   [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...  open  
7   [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
8   [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
11  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
12  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
15                                                 []  open  
16  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
17  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
21  [{'id': 60635328, 'node_id': 'MDU6TGFiZWw2MDYz...  open  
22                                                 []  open  
23  [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
24  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
25  [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
26  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
28  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
29  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open

### Exercício 10

In [6]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [2]:
import sqlite3

In [3]:
con =  sqlite3.connect('banco.bd')

In [15]:
query = """
    CREATE TABLE curso
    (id integer primary key,
    nome varchar (222))
    """

con.execute(query)

In [20]:
query = """
    INSERT INTO curso (nome) VALUES ('R')
    """
con.execute(query)

In [21]:
con.commit()

In [4]:
import pandas as pd

In [6]:
cursor = con.cursor()

cursor.execute("SELECT * FROM curso")


In [ ]:
df = pd.DataFrame(
df

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>